lab4: nutrition inflation e3_17 e3_23 e4_28

nutrition: nutrition.cpp
\tg++ -o nutrition nutrition.cpp
\t./nutrition

inflation: inflation.cpp
\tg++ -o inflation inflation.cpp
\t./Task2_while
e3_17: 3_17.cpp
\tg++ -o 3_17 3_17.cpp
\t./3_17
e3_23: 3_23.cpp
\tg++ -o 3_23 3_23.cpp
\t./3_23
e4_28: 4_28.cpp
\tg++ -o 4_28 4_28.cpp
\t./4_28
clean:
\trm inflation nutrition 3_17 4_28 3_23

