lab4: nutrition inflation e3_17 e3_23 e4_28

nutrition: nutrition.cpp
	g++ -o nutrition nutrition.cpp
	./nutrition

inflation: inflation.cpp
	g++ -o inflation inflation.cpp
	./inflation
e3_17: 3_17.cpp
	g++ -o 3_17 3_17.cpp
	./3_17
e3_23: 3_23.cpp
	g++ -o 3_23 3_23.cpp
	./3_23
e4_28: 4_28.cpp
	g++ -o 4_28 4_28.cpp
	./4_28
clean:
	rm inflation nutrition 3_17 4_28 3_23

