lab5: primeNums sumOfDigits linearRegression

sumOfDigits: sumOfDigits.cpp
	g++ -o sumOfDigits sumOfDigits.cpp
	./sumOfDigits
primeNums: primeNums.cpp
	g++ -o primeNums primeNums.cpp
	./primeNums
linearRegression: linearRegression.cpp
	g++ -o linearRegression linearRegression.cpp
	./linearRegression
clean:
	rm primeNums sumOfDigits linearRegression
